import {dateKey,addDays,displayQty,unitName,requirements,supplyPlan,escapeHTML as esc} from './logic.js';
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('ar-SA',{maximumFractionDigits:1}).format(Number(n||0)),money=n=>fmt(n)+' ر.س';
const icons={overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',branches:'M3 21h18M5 21V7h14v14M9 7V3h6v4M9 11h1m4 0h1m-6 4h1m4 0h1m-5 6v-3h4v3',forecast:'M3 18l6-6 4 3 8-11M15 4h6v6M3 22h18',inventory:'M3 7l9-4 9 4v11l-9 4-9-4zM3 7l9 5 9-5M12 12v10M8 5l9 5',waste:'M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14M10 11v6m4-6v6',recipes:'M4 3h12a3 3 0 0 1 3 3v15H7a3 3 0 0 1-3-3zM4 17h15M8 7h7m-7 4h5',pos:'M3 4h3l3 12h10l3-9H7M10 21h.01M18 21h.01',plus:'M12 4v16M4 12h16',alert:'M12 3L2 21h20zM12 9v5m0 3h.01',refresh:'M20 7v5h-5M4 17v-5h5M5 7a8 8 0 0 1 14-1l1 6M4 12l1 6a8 8 0 0 0 14-1',clock:'M12 8v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0'};
const icon=n=>`<span class="ico" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="${icons[n]||icons.inventory}"/></svg></span>`;
const nav=[['overview','نظرة عامة'],['branches','أداء الفروع'],['forecast','التنبؤ والتخطيط'],['inventory','المخزون والدفعات'],['waste','الهدر والجرد'],['recipes','الوجبات والوصفات']];
let state={page:'overview',branch:null,from:addDays(dateKey(),-6),to:dateKey(),day:dateKey(),data:null,token:'',cart:[],orderKey:crypto.randomUUID(),forecast:null,forecastDays:7,buffer:10,inventoryTab:'lots',busy:false};
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),5000);}
async function api(name,body={}){const r=await fetch('/api/'+name,{method:'POST',headers:{'Content-Type':'application/json','X-FoodSight-Token':state.token},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تنفيذ العملية');return d;}
function errorText(e){return esc(e.message||String(e));}
function name(type,id){return state.data?.[type]?.find(x=>x.id===Number(id))?.name||'';}
function quantity(q,id){return displayQty(q,state.data.ingredients.find(i=>i.id===Number(id))?.unit);}
function branchOptions(all=true,selected=state.branch){return `${all?'<option value="">جميع الفروع</option>':''}${state.data.branches.map(b=>`<option value="${b.id}" ${Number(selected)===b.id?'selected':''}>${esc(b.name)}</option>`).join('')}`;}
function ingredientOptions(selected){return state.data.ingredients.map(i=>`<option value="${i.id}" ${Number(selected)===i.id?'selected':''}>${esc(i.name)}</option>`).join('');}
function stat(label,value,note='',accent=false){return `<article class="card stat ${accent?'accent':''}"><div class="label">${label}</div><div class="value">${value}</div><div class="muted small">${note}</div></article>`;}
function table(headers,rows,empty='لا توجد بيانات في الفترة المحددة'){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">${empty}</td></tr>`}</tbody></table></div>`;}
function badge(text,color=''){return `<span class="badge ${color}">${text}</span>`;}
function filters(){return `<div class="filters"><label for="from">من</label><input id="from" type="date" value="${state.from}" max="${dateKey()}"><label for="to">إلى</label><input id="to" type="date" value="${state.to}" max="${dateKey()}"><button class="btn secondary small" data-action="dates">عرض الفترة</button><button class="btn secondary small" data-action="week">آخر 7 أيام</button><button class="btn secondary small" data-action="previous">الأسبوع السابق</button></div>`;}
function heading(title,sub,action=''){return `<div class="page-heading"><div><div class="eyebrow">${state.branch?esc(name('branches',state.branch)):'جميع الفروع'} / FoodSight</div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`;}
function lineChart(sales,forecast=false){const dates=[...new Set(sales.map(s=>s.sale_date||s.day))].sort();if(!dates.length)return '<div class="empty">لا توجد بيانات للرسم</div>';const values=dates.map(d=>sales.filter(s=>(s.sale_date||s.day)===d).reduce((a,s)=>a+Number(s.quantity??s.planned??0),0));const max=Math.max(...values,1)*1.2,W=640,H=200,pad=35,coords=values.map((v,i)=>[pad+i*(W-pad*2)/Math.max(1,values.length-1),H-pad-v/max*(H-pad*2)]);const points=coords.map(p=>p.join(',')).join(' ');return `<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${forecast?'توقع الوجبات':'عدد الوجبات المباعة'} حسب التاريخ">${[0,.5,1].map(t=>`<line class="axis" x1="35" x2="620" y1="${H-pad-t*(H-pad*2)}" y2="${H-pad-t*(H-pad*2)}"/><text x="26" y="${H-pad-t*(H-pad*2)+4}" text-anchor="end">${fmt(max*t)}</text>`).join('')}<polygon points="${pad},${H-pad} ${points} ${coords.at(-1)[0]},${H-pad}" fill="#FFB36B" opacity=".13"/><polyline points="${points}" fill="none" stroke="${forecast?'#FFB36B':'#28323C'}" stroke-width="3" stroke-linejoin="round"/>${coords.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="3.5" fill="#FFB36B"><title>${dates[i]}: ${values[i]}</title></circle>${i%Math.max(1,Math.ceil(dates.length/7))===0?`<text x="${p[0]}" y="194" text-anchor="middle">${dates[i].slice(5)}</text>`:''}`).join('')}</svg>`;}
function overview(){const d=state.data,total=d.sales.reduce((a,s)=>a+Number(s.revenue),0),sold=d.sales.reduce((a,s)=>a+s.quantity,0),wcost=d.waste.reduce((a,w)=>a+w.quantity*w.unit_cost,0),soon=d.lots.filter(l=>new Date(l.expires_at)-new Date()<86400000);return heading('قرار أوضح. هدر أقل.','تابع المبيعات والمخزون، واعرف ما يحتاج تدخلك اليوم.',`<button class="btn" data-action="receive">${icon('plus')}استلام مخزون</button>`)+filters()+`<div class="stats">${stat('إجمالي المبيعات',money(total),'خلال الفترة المحددة',true)}${stat('الوجبات المباعة',fmt(sold),'جميع الوجبات في الفترة')}${stat('تكلفة الهدر المسجل',money(wcost),'بسعر تكلفة المكونات')}${stat('دفعات تحتاج متابعة',fmt(soon.length),'منتهية أو تنتهي خلال 24 ساعة')}</div><div class="grid two"><section class="card"><div class="card-head"><h2>حركة المبيعات</h2><div class="legend"><span><i class="dot ink"></i>وجبات مباعة</span></div></div>${lineChart(d.sales)}</section><section class="card"><div class="card-head"><h2>يحتاج انتباهك</h2>${badge('المخزون الحالي','orange')}</div>${soon.slice(0,3).map(l=>`<div class="alert"><span class="alert-icon">${icon('clock')}</span><div><b>${esc(name('ingredients',l.ingredient_id))} · ${quantity(l.remaining,l.ingredient_id)}</b><p>${esc(name('branches',l.branch_id))} — ${new Date(l.expires_at)<new Date()?'انتهت الصلاحية؛ سجّل التصرف الفعلي':'تنتهي خلال 24 ساعة؛ راجع خطة الاستخدام'}</p><button class="btn secondary small" data-action="go-inventory">عرض الدفعات</button></div></div>`).join('')||'<p class="muted">لا توجد دفعات تنتهي خلال 24 ساعة.</p>'}<div class="alert"><span class="alert-icon">${icon('forecast')}</span><div><b>جهّز خطة الأسبوع</b><p>اعرف الطلب المتوقع والكميات الإضافية لكل فرع.</p><button class="btn secondary small" data-action="go-forecast">عرض التنبؤ</button></div></div></section></div><div class="card-head section-gap"><h2>الفروع في لمحة</h2><span class="muted small">اضغط الفرع لمراجعة يومه</span></div><div class="grid three">${d.branches.filter(b=>!state.branch||b.id===state.branch).map(b=>{const s=d.sales.filter(s=>s.branch_id===b.id),w=d.waste.filter(w=>w.branch_id===b.id);return `<button class="card branch" data-branch-card="${b.id}"><div class="row">${icon('branches')}<h3>${esc(b.name)}</h3><span class="spacer"></span>${badge(b.district)}</div><div class="branch-values"><div><b>${money(s.reduce((a,x)=>a+Number(x.revenue),0))}</b><span>المبيعات</span></div><div><b>${money(w.reduce((a,x)=>a+x.quantity*x.unit_cost,0))}</b><span>تكلفة الهدر</span></div></div></button>`;}).join('')}</div>`;}
function branches(){const d=state.data,s=d.sales.filter(x=>x.sale_date===state.day),w=d.waste.filter(x=>dateKey(new Date(x.created_at))===state.day),items=d.meals.map(m=>({meal_id:m.id,quantity:s.filter(x=>x.meal_id===m.id).reduce((a,x)=>a+x.quantity,0)})),needs=requirements(items,d.recipes);let start=state.from;return heading('تفاصيل اليوم','المبيعات، والاستهلاك حسب الوصفات، والهدر المسجل لكل يوم.')+filters()+`<div class="split-tabs"><button class="active">التشغيل اليومي</button><button data-action="go-forecast">التنبؤ والتخطيط</button></div><div class="row"><label for="detail-day">اليوم</label><input id="detail-day" type="date" value="${state.day}" min="${state.from}" max="${state.to}"></div><div class="day-list">${Array.from({length:Math.min(7,Math.floor((new Date(state.to)-new Date(start))/86400000)+1)},(_,i)=>addDays(start,i)).map(day=>`<button class="${day===state.day?'active':''}" data-day="${day}">${new Date(day+'T12:00:00').toLocaleDateString('ar-SA',{weekday:'short'})}<b>${fmt(Number(day.slice(-2)))}</b></button>`).join('')}</div><div class="stats">${stat('مبيعات اليوم',money(s.reduce((a,x)=>a+Number(x.revenue),0)),'حسب الفرع المحدد',true)}${stat('وجبات اليوم',fmt(items.reduce((a,x)=>a+x.quantity,0)))}${stat('هدر اليوم',money(w.reduce((a,x)=>a+x.quantity*x.unit_cost,0)),'التكلفة، وليست قيمة البيع')}${stat('حالات نفاد مسجلة',fmt(s.filter(x=>x.stockout).length),'تُستبعد من تدريب التنبؤ')}</div><div class="grid equal"><section class="card"><div class="card-head"><h2>الوجبات المباعة</h2></div>${table(['الوجبة','الكمية','القيمة'],items.map(x=>`<tr><td>${esc(name('meals',x.meal_id))}</td><td>${fmt(x.quantity)}</td><td>${money(s.filter(z=>z.meal_id===x.meal_id).reduce((a,z)=>a+Number(z.revenue),0))}</td></tr>`))}</section><section class="card"><div class="card-head"><h2>الاستهلاك حسب الوصفة</h2></div>${table(['المكون','المستهلك المحسوب'],needs.map(x=>`<tr><td>${esc(name('ingredients',x.ingredient_id))}</td><td>${quantity(x.quantity,x.ingredient_id)}</td></tr>`))}<p class="subtitle">الاستهلاك النظري يُقارن بالجرد الفعلي؛ فرق الجرد ليس هدرًا مؤكدًا.</p></section></div>`;}
function inventory(){const d=state.data;return heading('كل دفعة، بتفاصيلها.','المتبقي الحالي حسب الدفعة، مع الصلاحية وسجل كل حركة.',`<div class="row"><button class="btn secondary" data-action="bundle">تعبئة حسب الوجبات</button><button class="btn" data-action="receive">${icon('plus')}استلام مواد</button></div>`)+`<div class="split-tabs"><button class="${state.inventoryTab==='lots'?'active':''}" data-inv-tab="lots">الدفعات الحالية</button><button class="${state.inventoryTab==='moves'?'active':''}" data-inv-tab="moves">سجل الحركات</button></div>`+(state.inventoryTab==='lots'?`<section class="card">${table(['المكون / الدفعة','الفرع','المتبقي','انتهاء الصلاحية','الحالة','إجراء'],d.lots.map(l=>{const diff=(new Date(l.expires_at)-new Date())/86400000;return `<tr><td><b>${esc(name('ingredients',l.ingredient_id))}</b><div class="muted">${esc(l.lot_code)}</div></td><td>${esc(name('branches',l.branch_id))}</td><td>${quantity(l.remaining,l.ingredient_id)}</td><td>${new Date(l.expires_at).toLocaleString('ar-SA',{dateStyle:'short',timeStyle:'short'})}</td><td>${badge(diff<=0?'منتهية':diff<=1?'تنتهي قريبًا':'صالحة',diff<=0?'red':diff<=1?'orange':'green')}</td><td><div class="row"><button class="btn secondary small" data-waste="${l.id}">هدر</button><button class="btn secondary small" data-count="${l.id}">جرد</button>${diff>0?`<button class="btn secondary small" data-transfer="${l.id}">نقل</button>`:''}</div></td></tr>`;}))}</section><div class="info">الصلاحية تخص الدفعة نفسها. الدفعة المنتهية لا تُستخدم في البيع، ولا تُحسب هدرًا مسجلًا إلا بعد تسجيل الإتلاف.</div>`:filters()+`<section class="card">${table(['الوقت','المكون','الفرع','الحركة','الكمية','التفاصيل'],d.movements.map(m=>`<tr><td>${new Date(m.occurred_at).toLocaleString('ar-SA',{dateStyle:'short',timeStyle:'short'})}</td><td>${esc(name('ingredients',m.ingredient_id))}</td><td>${esc(name('branches',m.branch_id))}</td><td>${esc(({receipt:'استلام',sale:'بيع',waste:'هدر',adjustment:'تسوية جرد',transfer_in:'نقل وارد',transfer_out:'نقل صادر',historical_consumption:'استهلاك تاريخي'})[m.kind])}</td><td dir="ltr">${quantity(m.quantity,m.ingredient_id)}</td><td>${esc(m.note)}</td></tr>`))}<p class="subtitle">يعرض آخر 400 حركة في الفترة المحددة.</p></section>`);}
function waste(){const d=state.data;const reasons={};for(const w of d.waste)reasons[w.reason]=(reasons[w.reason]||0)+w.quantity*w.unit_cost;const max=Math.max(...Object.values(reasons),1);return heading('الهدر والجرد','سجّل السبب، ثم راجع أين يمكن خفض الخسارة.',`<button class="btn" data-action="go-inventory">تسجيل هدر أو جرد</button>`)+filters()+`<div class="grid equal"><section class="card"><div class="card-head"><h2>تكلفة الهدر حسب السبب</h2>${badge(money(Object.values(reasons).reduce((a,b)=>a+b,0)),'orange')}</div>${Object.entries(reasons).map(([r,v])=>`<div class="bar-row"><span>${esc(r)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><b>${fmt(v)}</b></div>`).join('')||'<p class="empty">لا يوجد هدر مسجل في الفترة.</p>'}</section><section class="card"><h2>كيف تقرأ الأرقام؟</h2><div class="alert"><div><b>الهدر المسجل</b><p>كمية أُتلفت فعليًا مع سبب وحركة خصم واحدة.</p></div></div><div class="alert"><div><b>المعرّض للتلف</b><p>مخزون لم يُستخدم قبل الصلاحية المتوقعة؛ تنبيه للتصرف، لا خسارة مسجلة.</p></div></div><div class="alert"><div><b>فرق الجرد</b><p>الكمية الفعلية ناقص المحسوبة. تُحفظ تسوية مستقلة مع تفسيرها.</p></div></div></section></div><section class="card section-gap"><div class="card-head"><h2>سجلات الهدر</h2></div>${table(['اليوم','الفرع','المكون','الكمية','التكلفة','السبب'],d.waste.slice().reverse().map(w=>`<tr><td>${dateKey(new Date(w.created_at))}</td><td>${esc(name('branches',w.branch_id))}</td><td>${esc(name('ingredients',w.ingredient_id))}</td><td>${quantity(w.quantity,w.ingredient_id)}</td><td>${money(w.quantity*w.unit_cost)}</td><td>${esc(w.reason)}</td></tr>`))}</section>`;}
function recipes(){const d=state.data;return heading('الوصفة هي أساس الحساب','كل بيع يتحول إلى استهلاك محدد من المكونات.')+`<div class="grid equal">${d.meals.map(m=>`<section class="card"><div class="card-head"><h2>${esc(m.name)}</h2>${badge(money(m.price),'orange')}</div>${d.recipes.filter(r=>r.meal_id===m.id).map(r=>`<span class="recipe-chip">${esc(name('ingredients',r.ingredient_id))} · ${quantity(r.quantity,r.ingredient_id)}</span>`).join('')}<p class="subtitle">الوصفة 1 · لكل وجبة واحدة</p></section>`).join('')}</div><div class="info neutral">الأوزان هنا افتراضات للمشروع. تحفظ كل عملية بيع رقم نسخة الوصفة المستخدمة؛ إضافة نسخة جديدة لاحقًا لا تغير المبيعات السابقة.</div>`;}
function forecasts(){let out=heading('خطط للأسبوع القادم','توقع المبيعات، ثم حوّلها إلى احتياج شراء وتحضير لكل فرع.')+`<div class="card"><div class="row"><label for="f-days">فترة التخطيط</label><select id="f-days">${[7,14,28].map(n=>`<option value="${n}" ${state.forecastDays===n?'selected':''}>${n} أيام</option>`).join('')}</select><label for="f-buffer">هامش الاحتياط %</label><input id="f-buffer" type="number" min="0" max="50" value="${state.buffer}"><span class="spacer"></span><button class="btn dark" data-action="forecast">${icon('forecast')}احسب التنبؤ</button></div><p class="subtitle">من اليوم · توزيع يومي يراعي صلاحية الدفعات ومدة التوريد.</p></div>`;if(!state.forecast)return out+`<div class="empty card section-gap">${icon('forecast')}<h2>التخطيط يبدأ من بياناتك</h2><p>اضغط «احسب التنبؤ» لتحليل الأيام المماثلة خلال السنة الماضية.</p></div>`;
const f=state.forecast,plan=supplyPlan(state.data,f),total=f.days.reduce((a,x)=>a+Number(x.predicted),0),missing=plan.filter(x=>x.missing>0),risk=plan.reduce((a,x)=>a+x.expiring*state.data.ingredients.find(i=>i.id===x.ingredient_id).unit_cost,0);
out+=`<div class="stats section-gap">${stat('وجبات متوقعة',fmt(total),'قبل هامش الاحتياط',true)}${stat('خطة التحضير',fmt(f.days.reduce((a,x)=>a+Number(x.planned),0)),'قبل خصم مبيعات اليوم')}${stat('احتياجات إضافية',fmt(missing.length),'مكون × فرع')}${stat('معرّض للتلف',money(risk),'حسب محاكاة الاستخدام والصلاحية')}</div><div class="grid two"><section class="card"><div class="card-head"><h2>توقع الوجبات يوميًا</h2>${badge('يشمل الاحتياط','orange')}</div>${lineChart(f.days,true)}</section><section class="card"><h2>أساس التوصية</h2><p class="model-notes section-gap">${esc(f.method)}</p><div class="info">توقع إحصائي مبسط، مبني على بيانات تجريبية. ليس نموذج ذكاء اصطناعي مدرّبًا على مطعم حقيقي.</div></section></div><section class="card section-gap"><div class="card-head"><h2>المخزون المناسب</h2>${badge('الشراء منفصل عن التحضير')}</div>${table(['الفرع / المكون','احتياج متبقٍ','تغطيه الدفعات','عجز متوقع','شراء مقترح','أول نقص / اطلب قبل','إجراء'],plan.map(x=>`<tr><td><b>${esc(name('ingredients',x.ingredient_id))}</b><div class="muted">${esc(name('branches',x.branch_id))}</div></td><td>${quantity(x.need,x.ingredient_id)}</td><td>${quantity(x.covered,x.ingredient_id)}</td><td>${x.missing?badge(quantity(x.missing,x.ingredient_id),'red'):'—'}</td><td>${quantity(x.quantity,x.ingredient_id)}</td><td>${x.firstShort?`${x.firstShort}<div class="muted">${x.orderBy}${x.orderBy<dateKey()?' · عاجل':''}</div>`:'—'}</td><td>${x.missing?`<button class="btn secondary small" data-purchase-branch="${x.branch_id}" data-purchase-ing="${x.ingredient_id}" data-purchase-qty="${x.quantity}" data-purchase-date="${x.firstShort}">جدولة توريد</button>`:'مغطى'}</td></tr>`))}<div class="info">تُستهلك الدفعات الأقرب انتهاءً أولًا، ويُقيَّم توفرها عند منتصف كل يوم. الشراء مقرب لحجم العبوة. للمكونات سريعة التلف، وزّع توريد الكمية على أيام الاحتياج؛ لا تستلم كمية الأسبوع دفعة واحدة. صلاحية التوريدات المنتظرة افتراضية إلى حين الاستلام.</div></section><section class="card section-gap"><div class="card-head"><h2>خطة التحضير اليومية</h2><button class="btn" data-action="save-plan">اعتماد خطة التحضير</button></div>${table(['اليوم','الفرع','الوجبة','المتوقع','نطاق وصفي','كمية الخطة'],f.days.map((x,i)=>`<tr><td>${x.day}</td><td>${esc(name('branches',x.branch_id))}</td><td>${esc(name('meals',x.meal_id))}</td><td>${fmt(x.predicted)}</td><td>${fmt(x.low)} – ${fmt(x.high)}</td><td><input aria-label="خطة ${esc(name('meals',x.meal_id))} ${x.day}" data-plan-index="${i}" type="number" min="0" step="1" value="${x.planned}"></td></tr>`))}</section>`;
return out+purchases();}
function purchases(){const p=state.data.purchases;return `<section class="card section-gap"><div class="card-head"><h2>توريدات منتظرة</h2>${badge(fmt(p.length))}</div>${table(['المكون','الفرع','الكمية','الوصول المتوقع','إجراء'],p.map(x=>`<tr><td>${esc(name('ingredients',x.ingredient_id))}</td><td>${esc(name('branches',x.branch_id))}</td><td>${quantity(x.quantity,x.ingredient_id)}</td><td>${esc(x.expected_on)}</td><td><button class="btn secondary small" data-receive-purchase="${x.id}">تسجيل الاستلام</button></td></tr>`))}<p class="subtitle">الطلب المنتظر لا يزيد المخزون الحالي قبل تسجيل الاستلام وتاريخ الصلاحية.</p></section>`;}
function pos(){const d=state.data,total=state.cart.reduce((a,x)=>a+x.quantity*d.meals.find(m=>m.id===x.meal_id).price,0);return heading('نقطة البيع التجريبية','كل طلب مكتمل يسجل البيع ويخصم مكوناته من الفرع المحدد.')+`<div class="info">الفرع: <b>${esc(name('branches',state.branch||1))}</b> · اختر فرعًا من الأعلى لتوجيه الطلب إليه. المخزون المنتهي لا يدخل في البيع.</div><div class="pos-grid"><div class="meal-grid">${d.meals.map(m=>`<button class="meal-card" data-add-meal="${m.id}"><div class="meal-symbol">${icon('recipes')}</div><b>${esc(m.name)}</b><span>${money(m.price)}</span><div class="subtitle">إضافة للطلب +</div></button>`).join('')}</div><section class="card"><div class="card-head"><h2>الطلب الحالي</h2><button class="btn secondary small" data-action="clear-cart">تفريغ</button></div>${state.cart.length?state.cart.map(x=>`<div class="cart-row"><div><b>${esc(name('meals',x.meal_id))}</b><div class="muted small">${money(d.meals.find(m=>m.id===x.meal_id).price*x.quantity)}</div></div><div class="qty-control"><button aria-label="تقليل" data-minus-meal="${x.meal_id}">−</button><span>${fmt(x.quantity)}</span><button aria-label="زيادة" data-add-meal="${x.meal_id}">+</button></div></div>`).join(''):'<div class="empty">اختر الوجبات لإضافتها إلى الطلب.</div>'}<div class="cart-total"><span>الإجمالي</span><span>${money(total)}</span></div><button class="btn full" data-action="checkout" ${!state.cart.length?'disabled':''}>إتمام الطلب وخصم المخزون</button><p class="subtitle">الأسعار تجريبية شاملة كما هي، دون فاتورة ضريبية.</p>${state.cart.length?`<div class="section-gap"><h3>سيُستهلك من المخزون</h3>${requirements(state.cart,d.recipes).map(x=>`<div class="row small"><span>${esc(name('ingredients',x.ingredient_id))}</span><span class="spacer"></span><b>${quantity(x.quantity,x.ingredient_id)}</b></div>`).join('')}</div>`:''}</section></div>`;}
function render(){if(!state.data)return;const renderers={overview,branches,inventory,waste,recipes,forecast:forecasts,pos};$('#app').innerHTML=`<div class="shell"><aside class="sidebar"><a href="#overview" aria-label="FoodSight الرئيسية"><img class="brand" src="/assets/logo.png" alt="FoodSight"></a><nav class="nav" aria-label="القائمة الرئيسية">${nav.map(([id,label])=>`<button data-page="${id}" class="${state.page===id?'active':''}">${icon(id)}${label}</button>`).join('')}</nav><div class="side-footer"><b>مساحة المشروع التجريبية</b><p>3 فروع · بيانات 365 يومًا<br>جميع البيانات مولّدة للعرض.</p></div></aside><div class="main"><header class="topbar"><div class="right"><button class="btn" data-page="pos">${icon('pos')}جرّب POS</button><select id="branch-select" aria-label="اختيار الفرع">${branchOptions(state.page!=='pos',state.branch|| (state.page==='pos'?1:null))}</select></div><div class="left"><span class="today muted small">${new Date().toLocaleDateString('ar-SA',{weekday:'long',day:'numeric',month:'long'})}</span><button class="btn secondary small" data-action="refresh" aria-label="تحديث البيانات">${icon('refresh')}</button></div></header><main class="content">${renderers[state.page]()}</main></div></div>`;}
async function refresh(){const d=await api('dashboard',{p_branch:state.branch,p_from:state.from,p_to:state.to});state.data=d;render();}
function modal(title,body,submit){const el=$('#modal');el.innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="close" aria-label="إغلاق" data-close>×</button></div><form class="form">${body}<div class="form-error" hidden></div><button type="submit" class="btn full">${submit||'حفظ'}</button></form>`;el.showModal();el.querySelector('[data-close]').onclick=()=>el.close();return el.querySelector('form');}
function onSubmit(form,fn){form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('[type=submit]'),err=form.querySelector('.form-error');b.disabled=true;err.hidden=true;try{await fn(new FormData(form));$('#modal').close();state.forecast=null;await refresh();toast('تم الحفظ وتحديث البيانات');}catch(e){err.textContent=e.message;err.hidden=false;}finally{b.disabled=false;}};}
function datetimeLocal(date){const d=new Date(date);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function receive(purchase=null){const form=modal('استلام مخزون',`<div class="twocol"><label>الفرع<select name="branch" ${purchase?'disabled':''}>${branchOptions(false,purchase?.branch_id||state.branch||1)}</select></label><label>المكون<select name="ingredient" ${purchase?'disabled':''}>${ingredientOptions(purchase?.ingredient_id||1)}</select></label></div><div class="twocol"><label>الكمية<input name="quantity" type="number" min="0.001" step="0.001" value="${purchase?.quantity||''}" required ${purchase?'readonly':''}></label><label>وحدة الإدخال<select name="unit"></select></label></div><label>انتهاء الصلاحية الفعلي<input name="expiry" type="datetime-local" required></label><div class="twocol"><label>رقم الدفعة<input name="code" value="LOT-${Date.now().toString().slice(-8)}" maxlength="80" required></label><label>المورد<input name="supplier" placeholder="اسم المورد" maxlength="120"></label></div><p class="muted small">أدخل الصلاحية من بيانات الدفعة. لا تُستخدم مدد العرض الافتراضية كتعليمات حفظ غذائي.</p>`,'تسجيل الاستلام');const ing=form.elements.ingredient,unit=form.elements.unit;const update=()=>{const i=state.data.ingredients.find(x=>x.id===Number(ing.value));unit.innerHTML=[i.unit,...(purchase?[]:i.unit==='g'?['kg','pack']:i.unit==='ml'?['l','pack']:['pack'])].map(u=>`<option value="${u}">${unitName(u)}${u==='pack'?' ('+displayQty(i.pack_size,i.unit)+')':''}</option>`).join('');};ing.onchange=update;update();onSubmit(form,fd=>api('receive_stock',{p_branch:purchase?.branch_id||Number(fd.get('branch')),p_ingredient:purchase?.ingredient_id||Number(fd.get('ingredient')),p_quantity:Number(fd.get('quantity')),p_unit:fd.get('unit'),p_expiry:new Date(fd.get('expiry')).toISOString(),p_code:fd.get('code'),p_supplier:fd.get('supplier'),p_purchase:purchase?.id||null}));}
function lotAction(kind,id){const l=state.data.lots.find(l=>l.id===id),i=state.data.ingredients.find(i=>i.id===l.ingredient_id),titles={waste:'تسجيل هدر',count:'جرد وتسوية',transfer:'نقل بين الفروع'};const form=modal(titles[kind],`<div class="info">${esc(i.name)} · ${esc(name('branches',l.branch_id))}<br>المتبقي: ${displayQty(l.remaining,i.unit)}<br>الدفعة: ${esc(l.lot_code)}</div>${kind==='transfer'?`<label>الفرع المستلم<select name="branch">${state.data.branches.filter(b=>b.id!==l.branch_id).map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></label>`:''}<label>${kind==='count'?'الكمية الفعلية بعد الجرد':'الكمية'} (${unitName(i.unit)})<input name="quantity" type="number" step="0.001" min="${kind==='count'?0:0.001}" ${kind!=='count'?`max="${l.remaining}"`:''} required></label>${kind!=='transfer'?`<label>${kind==='count'?'تفسير فرق الجرد':'سبب الهدر'}<input name="reason" required minlength="2" maxlength="200" list="reasons"><datalist id="reasons"><option>انتهاء الصلاحية</option><option>فائض تحضير</option><option>تلف أثناء التجهيز</option><option>فرق جرد غير مفسر</option></datalist></label>`:'<p class="muted small">يحفظ النقل صلاحية الدفعة الأصلية وتكلفتها. نفّذ النقل الفعلي وفق شروط الحفظ المعتمدة.</p>'}`);onSubmit(form,fd=>api({waste:'record_waste',count:'count_stock',transfer:'transfer_stock'}[kind],{p_lot:id,...(kind==='count'?{p_actual:Number(fd.get('quantity'))}:{p_quantity:Number(fd.get('quantity'))}),...(kind==='transfer'?{p_branch:Number(fd.get('branch'))}:{p_reason:fd.get('reason')})}));}
function bundle(){const form=modal('تعبئة مخزون حسب الوجبات',`<label>الفرع<select name="branch">${branchOptions(false,state.branch||1)}</select></label><div class="twocol"><label>الوجبة<select name="meal">${state.data.meals.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></label><label>عدد الوجبات<input name="count" type="number" min="1" max="10000" step="1" value="30" required></label></div><div id="bundle-lines"></div><p class="muted small">هذا استلام فعلي للمكونات المحسوبة، وليس تسجيل إنتاج وجبات. أدخل صلاحية كل مكون كما هو مستلم.</p>`,'استلام جميع المكونات');let needs=[];const update=()=>{needs=requirements([{meal_id:Number(form.elements.meal.value),quantity:Number(form.elements.count.value)}],state.data.recipes);$('#bundle-lines').innerHTML=needs.map(x=>`<label>${esc(name('ingredients',x.ingredient_id))} — ${quantity(x.quantity,x.ingredient_id)}<input name="expiry-${x.ingredient_id}" type="datetime-local" required aria-label="صلاحية ${esc(name('ingredients',x.ingredient_id))}"></label>`).join('');};form.elements.meal.onchange=update;form.elements.count.onchange=update;update();onSubmit(form,fd=>api('receive_bundle',{p_branch:Number(fd.get('branch')),p_lines:needs.map(x=>({ingredient_id:x.ingredient_id,quantity:x.quantity,expiry:new Date(fd.get('expiry-'+x.ingredient_id)).toISOString()})),p_code:'MEAL-'+Date.now()}));}
function purchaseForm(el){const branch=Number(el.dataset.purchaseBranch),ing=Number(el.dataset.purchaseIng),qty=Number(el.dataset.purchaseQty),i=state.data.ingredients.find(x=>x.id===ing);const form=modal('جدولة توريد',`<div class="info">${esc(name('branches',branch))} · ${esc(i.name)}<br>مدة التوريد: ${fmt(i.lead_days)} يوم</div><label>الكمية (${unitName(i.unit)})<input name="quantity" type="number" min="1" step="0.001" value="${qty}" required></label><label>موعد الوصول المتوقع<input name="date" type="date" min="${dateKey()}" value="${addDays(dateKey(),i.lead_days)}" required></label><p class="muted small">نقص متوقع من ${esc(el.dataset.purchaseDate)}. للمواد سريعة التلف سجّل توريدات أصغر موزعة على أيام الاحتياج.</p>`,'حفظ التوريد المنتظر');onSubmit(form,fd=>api('purchase',{branch_id:branch,ingredient_id:ing,quantity:Number(fd.get('quantity')),expected_on:fd.get('date')}));}
async function navigate(page){state.page=page;if(page==='pos'&&!state.branch){state.branch=1;state.forecast=null;await refresh();}else render();location.hash=page;}
document.addEventListener('click',async e=>{const el=e.target.closest('button');if(!el)return;try{
 if(el.dataset.page){await navigate(el.dataset.page);return;}
 if(el.dataset.branchCard){state.branch=Number(el.dataset.branchCard);state.page='branches';state.forecast=null;await refresh();return;}
 if(el.dataset.day){state.day=el.dataset.day;render();return;}
 if(el.dataset.invTab){state.inventoryTab=el.dataset.invTab;render();return;}
 for(const kind of ['waste','count','transfer'])if(el.dataset[kind]){lotAction(kind,el.dataset[kind]);return;}
 if(el.dataset.purchaseBranch){purchaseForm(el);return;}
 if(el.dataset.receivePurchase){receive(state.data.purchases.find(x=>x.id===el.dataset.receivePurchase));return;}
 if(el.dataset.addMeal||el.dataset.minusMeal){const id=Number(el.dataset.addMeal||el.dataset.minusMeal),existing=state.cart.find(x=>x.meal_id===id);if(existing)existing.quantity+=el.dataset.addMeal?1:-1;else state.cart.push({meal_id:id,quantity:1});state.cart=state.cart.filter(x=>x.quantity>0);state.orderKey=crypto.randomUUID();render();return;}
 const a=el.dataset.action;if(!a)return;
 if(a.startsWith('go-')){await navigate(a.slice(3));return;}
 if(a==='receive'){receive();return;}if(a==='bundle'){bundle();return;}
 if(a==='clear-cart'){state.cart=[];state.orderKey=crypto.randomUUID();render();return;}
 el.disabled=true;
 if(a==='refresh'){state.forecast=null;await refresh();toast('تم تحديث البيانات');}
 if(a==='dates'){const from=$('#from').value,to=$('#to').value;if(!from||!to||from>to||to>dateKey())throw Error('اختر فترة صحيحة حتى اليوم');state.from=from;state.to=to;state.day=to;await refresh();}
 if(a==='week'){state.from=addDays(dateKey(),-6);state.to=dateKey();state.day=state.to;await refresh();}
 if(a==='previous'){state.from=addDays(state.from,-7);state.to=addDays(state.to,-7);state.day=state.to;await refresh();}
 if(a==='forecast'){state.forecastDays=Number($('#f-days').value);state.buffer=Number($('#f-buffer').value);if(state.buffer<0||state.buffer>50)throw Error('هامش الاحتياط بين 0 و50');state.forecast=await api('forecast',{p_branch:state.branch,p_start:dateKey(),p_days:state.forecastDays,p_buffer:state.buffer/100});render();}
 if(a==='save-plan'){const rows=state.forecast.days.map(x=>({branch_id:x.branch_id,meal_id:x.meal_id,plan_date:x.day,quantity:Number(x.planned)}));await api('save_plan',{rows});toast('تم حفظ خطة التحضير في قاعدة البيانات');}
 if(a==='checkout'){const saved=await api('place_order',{p_branch:state.branch||1,p_items:state.cart,p_request:state.orderKey});state.cart=[];state.orderKey=crypto.randomUUID();state.forecast=null;await refresh();toast(saved.duplicate?'هذا الطلب مسجل مسبقًا؛ لم يتكرر الخصم':'تم الطلب وخصم المخزون من '+name('branches',state.branch||1));}
 }catch(err){toast(err.message);}finally{el.disabled=false;}});
document.addEventListener('change',async e=>{const el=e.target;try{if(el.id==='branch-select'){state.branch=el.value?Number(el.value):null;state.forecast=null;state.cart=[];state.orderKey=crypto.randomUUID();await refresh();}if(el.id==='detail-day'){state.day=el.value;render();}if(el.dataset.planIndex!==undefined){const value=Number(el.value);if(!Number.isInteger(value)||value<0)throw Error('أدخل كمية صحيحة');state.forecast.days[Number(el.dataset.planIndex)].planned=value;render();}}catch(err){toast(err.message);}});
function connectionScreen(){
$('#app').innerHTML=`<section class="setup"><img src="/assets/logo.png" alt="FoodSight"><h1>اربط قاعدة البيانات مرة واحدة</h1><p>لا تحتاج حسابًا أو تسجيل دخول داخل التطبيق. أضف مفتاح مشروعك المحلي، وبعدها يفتح FoodSight مباشرة كل مرة.</p><p><a href="https://supabase.com/dashboard/project/ksemtrbeouvagobyrbvi/settings/api-keys" target="_blank" rel="noreferrer">افتح مفاتيح مشروع FoodSight في Supabase</a> وانسخ <b>Secret key</b> أو <b>service_role</b>.</p><form id="connection-form" class="form section-gap"><label>مفتاح الاتصال<input name="key" type="password" autocomplete="off" required placeholder="sb_secret_…"></label><div class="form-error" hidden></div><button type="submit" class="btn full">حفظ الاتصال وفتح التطبيق</button></form><p class="small muted">يُحفظ المفتاح على جهازك في ملف .env فقط، ولا يُعرض في الواجهة. لا ترسل هذا الملف لأحد.</p></section>`;
$('#connection-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button'),err=f.querySelector('.form-error');b.disabled=true;err.hidden=true;try{await api('configure',{key:new FormData(f).get('key')});f.reset();await boot();}catch(e){err.textContent=e.message;err.hidden=false;}finally{b.disabled=false;}};
}
async function boot(){try{const status=await(await fetch('/api/status')).json();state.token=status.token;if(!status.configured){if(status.hosted){$('#app').innerHTML='<section class="setup"><img src="/assets/logo.png" alt="FoodSight"><h1>جارٍ تجهيز اتصال المشروع</h1><p>يحتاج مالك الموقع إلى إضافة إعداد اتصال قاعدة البيانات في Vercel لإكمال التشغيل.</p></section>';}else connectionScreen();return;}state.page=nav.some(([p])=>p===location.hash.slice(1))?location.hash.slice(1):'overview';await refresh();}catch(e){$('#app').innerHTML=`<section class="setup"><img src="/assets/logo.png" alt="FoodSight"><h1>تعذر الاتصال</h1><p>${errorText(e)}</p><p>تحقق من الإنترنت ومفتاح الاتصال المحلي ثم حاول مجددًا.</p><button class="btn" id="retry">إعادة المحاولة</button></section>`;$('#retry').onclick=boot;}}
boot();
